apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: gh9ispj9o-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c9e88f742f.kmlz.p3.openshiftapps.com/rhtap/rhtap-qe:e6f6e449e1259668004427eee3cd97255dab1ce6@sha256:cb74085555e48304979edb4cf2f23019f78db099f8e8ea7281970bead612db42
          name: container-image
